kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ray-workflows-claim
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - {{ .Values.storage.accessMode | default "ReadWriteMany" }}
  resources:
    requests:
      storage: 20Gi

{{- if and (or (not .Values.storage.storageClassName) (eq .Values.storage.storageClassName "")) .Values.storage.pvLabelKey }}
  selector:
    matchLabels:
      pv-label-key: {{ .Values.storage.pvLabelKey }}
{{- else }}
  storageClassName: {{ .Values.storage.storageClassName }}
{{- end }}
