{{- if .Values.backend.database_enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: database-data-2
  name: database-data-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: {{ .Values.db.storageClassName | default "default" }}
status: {}
{{- end }}
